TODO:
  automate Faction rep gain
  automate augments
  automate home server upgrades
  cut ram usage to 32GB
  automate sharing ram with factions
  fix getting stuck if it cant fill up a server
  dont wait for all batches to finish (requires server list persistence between loops)

Factions:
  Stage 1:
    CyberSec
    Tian Di Hui
    Netburners
    Sector-12
  Stage 2:
    NiteSec
    The Black Hand
  Stage 3:
    BitRunners
  Stage 4:
    Daedalus
  Stage 5:
    Daedalus